# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'startwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_startwindow(object):
    def setupUi(self, startwindow):
        startwindow.setObjectName("startwindow")
        startwindow.resize(700, 500)
        startwindow.setMaximumSize(QtCore.QSize(700, 500))
        startwindow.setStyleSheet("\n"
"QWidget#centralwidget{\n"
"background-color: rgb(0, 0, 127);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(startwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 30, 600, 150))
        self.label.setMaximumSize(QtCore.QSize(600, 150))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        self.label.setMouseTracking(False)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(False)
        self.label.setIndent(-5)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(50, 210, 93, 28))
        self.pushButton.setObjectName("pushButton")
        startwindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(startwindow)
        QtCore.QMetaObject.connectSlotsByName(startwindow)

    def retranslateUi(self, startwindow):
        _translate = QtCore.QCoreApplication.translate
        startwindow.setWindowTitle(_translate("startwindow", "startwindow"))
        self.pushButton.setText(_translate("startwindow", "next window"))
